#!/usr/bin/env ruby

# Start the process to perform Paypal testing
# including IPN notifications to your development
# computer.
#
# This requires two arguments: the id of your Paypal
# sandbox, and you email
#
# Hence, usage:
#
#    start_paypal '<your paypal sandbox ID>'  '<your email address>'
#
require_relative 'lib/router'

process_id =  "exec 'bin/router #{ARGV[0]} #{ARGV[1]}'"
File.write(Router::PROCESS_FILE_NAME, process_id, nil, nil)
puts 'Paypal testing has started'
